### ISSUE TITLE
mysterious rectangle on Settings page, and unidentified first field

### ISSUE THREAD

**Issue by drpiccioni** [BaySchoolCS2/ProjectRepo#114]
git pull approx 1:10 PM 5/26/15
deleted database
signed up
logged in
verified email
submitted a post
see the post
clicked Settings
rectangle covers(?) an identifier for the first data-entry field.

**Comment by drpiccioni** [comment]
Not very important, but nice to have.

**Comment by michardy** [comment]
better?
![explination](https://cloud.githubusercontent.com/assets/11617907/7875659/96e12840-0574-11e5-8b2e-aba252e303cb.png)
