### ISSUE TITLE
404 Error not Displaying 

### ISSUE THREAD

**Issue by edburke16** [BaySchoolCS2/ProjectRepo#20]

**Comment by edburke16** [comment]
Well, I'm getting a 404 error whenever I go to a user page that does not exist. For once, that is a good thing! Issue closed for now at least.

**Comment by michardy** [comment]
I am getting 404 error for users that exist

**Comment by fhebert-perkins** [comment]
I just fixed this issue. So. Many. Problems. Not all @edburke16 's fault. 

fixed at 6323e306

will still get 404 when something does not exist
