### ISSUE TITLE
Add links to users on main page post list?

### ISSUE THREAD

**Issue by michardy** [BaySchoolCS2/ProjectRepo#53]
![screen shot 2015-05-01 at 19 11 55](https://cloud.githubusercontent.com/assets/11617907/7439578/09b1fff6-f036-11e4-9ca0-46f121e68230.png)
![mobile](https://cloud.githubusercontent.com/assets/11617907/7439596/838e202a-f036-11e4-9d0d-b314bc415e1c.png)
Feedback?
Anything else we need to fix issue: https://github.com/BaySchoolCS2/ProjectRepo/issues/25 ?

**Comment by fhebert-perkins** [comment]
I dont understand what you are saying here...

**Comment by michardy** [comment]
Already done
