### ISSUE TITLE
Different collections for tool and application

### ISSUE THREAD

**Issue by fhebert-perkins** [BaySchoolCS2/ProjectRepo#6]
As reported by @michardy there seems to be a issue with the tools for clearing databases and such. I would suggest using mongoengine instead of pymongo as it is the underlying api for flask-pymongo which is used by the actual application.

**Comment by michardy** [comment]
I just fixed this issue it was a problem of inconsistent capitalization in the code.

Sincerely,
Michael Hardy

**Comment by fhebert-perkins** [comment]
Ok, have you tested to make sure it works. If you have I'd be happy to see this issue closed out. Meanwhile I'm  going to go learn emacs
