### ISSUE TITLE
Filling in Dashboard with Followers and Post from Follwers

### ISSUE THREAD

**Issue by MJPenny** [BaySchoolCS2/ProjectRepo#62]

**Comment by MJPenny** [comment]
Is there anything the people want in the dashboard?

**Comment by michardy** [comment]
A list of posts by people you follow.
Any other ideas?

**Comment by MJPenny** [comment]
I added all post to Dashboard, but I was wondering on how to make it follower only

**Comment by fhebert-perkins** [comment]
you can filter by users so there is that.
