### ISSUE TITLE
Display toolbar on signup page

### ISSUE THREAD

**Issue by drpiccioni** [BaySchoolCS2/ProjectRepo#65]
... so that, e.g., after finding out your username is taken, you can go back to home page.

**Comment by fhebert-perkins** [comment]
It should automatically go to the homepage if you successfully signup

**Comment by fhebert-perkins** [comment]
Confirmed that it happens as it should. Not sure what the issue is

**Comment by michardy** [comment]
![screen shot 2015-05-06 at 16 07 24](https://cloud.githubusercontent.com/assets/11617907/7505654/06054976-f40a-11e4-9b60-7df424dd8928.png)
There should be a tool bar along the top with at least the homepage linked.

**Comment by fhebert-perkins** [comment]
Perhaps the signup should be a popup?
