### ISSUE TITLE
Mobile Style

### ISSUE THREAD

**Issue by fhebert-perkins** [BaySchoolCS2/ProjectRepo#71]
We should have dedicated mobile style. While Bootstrap does do some it can look pretty wacky on mobile so we should make sure that everything has a mobile counterpart that looks good.

**Comment by michardy** [comment]
Yes we need a mobile style.  The website is currently microscopic on Firefox or Chrome for Android.

**Comment by michardy** [comment]
Duplicate of larger issue:
https://github.com/BaySchoolCS2/ProjectRepo/issues/42
