### ISSUE TITLE
There are big words on the readme.md

### ISSUE THREAD

**Issue by fhebert-perkins** [BaySchoolCS2/ProjectRepo#8]
and im scared of big words... Will someone fix them?

**Comment by michardy** [comment]
Is this really an important issue

**Comment by fhebert-perkins** [comment]
Hey im trying to make issues that people will actually be able to fix. i.e not you @michardy
its simple yes,
is it a problem yes,
are me or you going to fix it? no

**Comment by edburke16** [comment]
Fixed it.
